### ISSUE TITLE
stragen generation with provided checkpoints

### ISSUE THREAD

**Issue by JialeTao** [xingzhehe/GANSeg#1]
Hi, thanks for sharing the good work. I used the provided checkpoints celeb_wild_k8 and taichi_k10 to generate images. It seems both the results are strange and are not natural images. I show some cases in the following.

celeb
![0](https://user-images.githubusercontent.com/38600167/172091624-f2aa7370-0f65-48d8-a0aa-12779c78dc4e.png)
![1](https://user-images.githubusercontent.com/38600167/172091631-a789d646-da4a-4aae-8296-396984145693.png)

taichi
![0](https://user-images.githubusercontent.com/38600167/172091657-ee6f69b9-9b32-41f9-a5b6-423925db363b.png)
![1](https://user-images.githubusercontent.com/38600167/172091662-e1d2d8d7-8e46-4b88-adfb-14c6a1e3cb8a.png)

BTW, I use the torch version 1.6.

**Comment by xingzhehe** [comment]
Thanks for bringing this up. It took me quite some time to fix. Please check the latest version.

I believe this is a bug caused by my code cleaning. BTW, even now, I don't know why it causes a bug since it is just a different writing way. You can check the `self.gen_keypoints_embedding_noise`, `self.gen_keypoints_layer` and `self.gen_background_embedding` in `generator.py`. 

If you got any further problems, don't hesitate to contact me.

**Comment by JialeTao** [comment]
Thanks for quick reply! After modify these three components, it works now.

It seems the generated images are much more natural now, but there still exists many artifacts, and some bodies are deformed. Is this normal?  Since some parts are missed, does it hurt the performance on the segmentation? 

![39](https://user-images.githubusercontent.com/38600167/172136242-0d6347b7-3617-41ca-a022-b87a9737999e.png)
![40](https://user-images.githubusercontent.com/38600167/172136278-f8a5d9b8-975a-44d2-a896-d4903f71e1fc.png)
![41](https://user-images.githubusercontent.com/38600167/172136303-854a05d1-b8ad-43f4-941e-7bc03dd163bc.png)
![42](https://user-images.githubusercontent.com/38600167/172136326-a9e0cb80-6f18-4751-9815-3711aaa4346d.png)
![43](https://user-images.githubusercontent.com/38600167/172136350-9fd56a3c-8e8d-412d-b022-76cc0d9e197d.png)
![44](https://user-images.githubusercontent.com/38600167/172136390-f9bd3d30-64b5-46df-996a-3c4b9729e323.png)

**Comment by xingzhehe** [comment]
I unrolled all the modules to hard-coded ones (please update). It works better now. I doubt it is a bug in Pytorch, not sure if it is due to the version.

There are still artifacts, which is normal since I do not use any path regularization or EMA or EqualLinear for simplifity. It may harm the quality of segmentation, but we just found the current one is enough for a SOTA performance.
